---
apiVersion: v1
kind: Service
metadata:
  name: fabric-voyager
  namespace: minecraft
spec:
  #type: ClusterIP
  type: NodePort
  ports:
  - name: fabric
    port: 25565
    targetPort: 25565
    nodePort: 30565
    protocol: TCP
  selector:
    app: fabric-voyager